### ISSUE TITLE
Didn't compile on Ubuntu 22.04

### ISSUE THREAD

**Issue by gnarlin** [Kljunas2/activate-linux#4]
Package gtk+-3.0 was not found in the pkg-config search path.
Perhaps you should add the directory containing `gtk+-3.0.pc'
to the PKG_CONFIG_PATH environment variable
No package 'gtk+-3.0' found
Package gtk+-3.0 was not found in the pkg-config search path.
Perhaps you should add the directory containing `gtk+-3.0.pc'
to the PKG_CONFIG_PATH environment variable
Package 'gtk+-3.0', required by 'gtk-layer-shell-0', not found
mkdir -p bin
gcc src/activate_linux.c -o bin/activate-linux 
In file included from src/activate_linux.c:1:
/usr/include/gtk-layer-shell/gtk-layer-shell.h:15:10: fatal error: gtk/gtk.h: No such file or directory
   15 | #include <gtk/gtk.h>
      |          ^~~~~~~~~~~
compilation terminated.
make: *** [Makefile:8: activate-linux] Error 1

I already installed: libgtk-layer-shell-dev libgtk-layer-shell0 to try to fix this.

**Comment by panekj** [comment]
you need [`libgtk-3-dev`](https://packages.ubuntu.com/jammy/libgtk-3-dev)
